import {
  ChangeEvent,
  useEffect,
  useRef,
} from "react";

import { useForm } from "react-hook-form";

import {
  Project,
  ProjectImage,
  normalizeProjectImages,
} from "../../../../types/project";

import { ProjectFormData } from "../../../../types/project-form";

import { useProjectUpload } from "../../../../hooks/useProjectUpload";

import { ProjectInfo } from "./ProjectInfo";
import { ProjectCover } from "./ProjectCover";
import { ProjectGallery } from "./ProjectGallery";
import { ProjectSettings } from "./ProjectSettings";

import * as S from "./styles";

interface Props {
  project?: Project;

  onSubmit(
    data: ProjectFormData
  ): Promise<void> | void;

  loading?: boolean;

  fieldErrors?: Record<
    string,
    string
  >;
}

const MAX_IMAGE_SIZE =
  10 * 1024 * 1024;

const MAX_GALLERY_IMAGES = 20;

function normalizeSlug(
  value: string
) {
  return value
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(
      /[\u0300-\u036f]/g,
      ""
    )
    .replace(
      /[^a-z0-9]+/g,
      "-"
    )
    .replace(
      /^-+|-+$/g,
      "");
}

export function ProjectForm({
  project,
  onSubmit,
  loading = false,
  fieldErrors = {},
}: Props) {
  const {
    register,
    handleSubmit,
    watch,
    setValue,
    reset,
    formState: {
      errors,
    },
  } = useForm<ProjectFormData>({
    defaultValues: {
      title: "",
      slug: "",
      category: "RESIDENTIAL",
      city: "",
      state: "",
      year: undefined,
      area: "",
      description: "",
      content: "",
      featuredImage: null,
      featuredImageStorageKey: null,
      videoUrl: null,
      published: true,
      featured: false,
      images: [],
    },
  });

  const {
    upload,
    uploading,
  } = useProjectUpload();

  const title =
    watch("title");

  const featuredImage =
    watch("featuredImage");

  const images =
    watch("images") ?? [];

  /**
   * Guarda o último slug
   * gerado automaticamente.
   *
   * Isso permite distinguir:
   *
   * slug gerado pelo título
   * x
   * slug editado manualmente.
   */
  const lastAutoGeneratedSlug =
    useRef("");

  /**
   * Indica se o usuário
   * alterou o slug manualmente.
   */
  const slugManuallyEdited =
    useRef(false);

  /**
   * Gera slug automaticamente
   * somente enquanto o usuário
   * não tiver editado o campo.
   */
  useEffect(() => {
    if (project) {
      return;
    }

    if (
      slugManuallyEdited.current
    ) {
      return;
    }

    const slug =
      normalizeSlug(
        title ?? ""
      );

    lastAutoGeneratedSlug.current =
      slug;

    setValue(
      "slug",
      slug,
      {
        shouldDirty: false,
      }
    );
  }, [
    title,
    project,
    setValue,
  ]);

  /**
   * Preenche o formulário
   * quando estamos editando
   * um projeto existente.
   */
  useEffect(() => {
    if (!project) {
      reset();

      lastAutoGeneratedSlug.current =
        "";

      slugManuallyEdited.current =
        false;

      return;
    }

    reset({
      title: project.title,

      slug: project.slug,

      category:
        project.category,

      city:
        project.city ?? "",

      state:
        project.state ?? "",

      year:
        project.year ??
        undefined,

      area:
        project.area ?? "",

      description:
        project.description,

      content:
        project.content ?? "",

      featuredImage:
        project.featuredImage ??
        null,

      featuredImageStorageKey:
        project.featuredImageStorageKey ??
        null,

      videoUrl:
        project.videoUrl ??
        null,

      published:
        project.published,

      featured:
        project.featured,

      images:
        normalizeProjectImages(
          project.images
        ),
    });

    lastAutoGeneratedSlug.current =
      project.slug;

    slugManuallyEdited.current =
      false;
  }, [
    project,
    reset,
  ]);

  /**
   * Remove a imagem de capa
   * do formulário.
   */
  function handleCoverRemove() {
    setValue(
      "featuredImage",
      null
    );

    setValue(
      "featuredImageStorageKey",
      null
    );
  }

  /**
   * Upload da imagem de capa.
   */
  async function handleCoverUpload(
    event: ChangeEvent<HTMLInputElement>
  ) {
    const file =
      event.target.files?.[0];

    if (!file) {
      return;
    }

    if (file.size === 0) {
      alert(
        "A imagem de capa está vazia e não pode ser enviada."
      );

      event.target.value = "";

      return;
    }

    if (
      file.size >
      MAX_IMAGE_SIZE
    ) {
      alert(
        "A imagem de capa deve ter no máximo 10 MB."
      );

      event.target.value = "";

      return;
    }

    try {
      const result =
        await upload(file);

      setValue(
        "featuredImage",
        result.imageUrl
      );

      setValue(
        "featuredImageStorageKey",
        result.storageKey
      );
    } catch (error) {
      console.error(
        "Erro ao enviar imagem de capa:",
        error
      );

      alert(
        "Não foi possível enviar a imagem de capa."
      );
    } finally {
      event.target.value = "";
    }
  }

  /**
   * Upload das imagens da galeria.
   */
  async function handleGalleryUpload(
    event: ChangeEvent<HTMLInputElement>
  ) {
    const files =
      event.target.files;

    if (!files?.length) {
      return;
    }

    if (
      images.length +
        files.length >
      MAX_GALLERY_IMAGES
    ) {
      alert(
        `Um projeto pode ter no máximo ${MAX_GALLERY_IMAGES} imagens na galeria.`
      );

      event.target.value = "";

      return;
    }

    const uploaded: ProjectImage[] =
      [];

    try {
      for (
        const file of Array.from(
          files
        )
      ) {
        if (file.size === 0) {
          alert(
            `A imagem "${file.name}" está vazia e não pode ser enviada.`
          );

          continue;
        }

        if (
          file.size >
          MAX_IMAGE_SIZE
        ) {
          alert(
            `A imagem "${file.name}" deve ter no máximo 10 MB.`
          );

          continue;
        }

        try {
          const result =
            await upload(file);

          /**
           * Impede que a capa atual
           * seja adicionada novamente
           * à galeria.
           */
          const currentFeaturedStorageKey =
            watch(
              "featuredImageStorageKey"
            );

          if (
            currentFeaturedStorageKey &&
            result.storageKey ===
              currentFeaturedStorageKey
          ) {
            alert(
              `A imagem "${file.name}" já é a imagem de capa e não pode ser adicionada à galeria.`
            );

            continue;
          }

          /**
           * Impede duplicação dentro
           * do próprio lote.
           */
          const alreadyUploaded =
            uploaded.some(
              (image) =>
                image.storageKey ===
                result.storageKey
            );

          if (
            alreadyUploaded
          ) {
            continue;
          }

          uploaded.push({
            imageUrl:
              result.imageUrl,

            storageKey:
              result.storageKey,

            alt:
              file.name,

            sortOrder:
              images.length +
              uploaded.length,
          });
        } catch (error) {
          console.error(
            `Erro ao enviar ${file.name}:`,
            error
          );

          alert(
            `Não foi possível enviar a imagem "${file.name}".`
          );
        }
      }

      if (
        uploaded.length > 0
      ) {
        setValue(
          "images",
          [
            ...images,
            ...uploaded,
          ]
        );
      }
    } finally {
      event.target.value = "";
    }
  }

  /**
   * Remove uma imagem da galeria.
   */
  function removeImage(
    index: number
  ) {
    setValue(
      "images",
      images.filter(
        (_, i) =>
          i !== index
      )
    );
  }

  /**
   * Marca o slug como
   * alterado manualmente.
   */
  function handleSlugChange() {
    slugManuallyEdited.current =
      true;
  }

  /**
   * Normaliza o slug antes
   * de enviar para a API.
   */
  function handleFormSubmit(
    data: ProjectFormData
  ) {
    const normalizedData: ProjectFormData =
      {
        ...data,

        slug: normalizeSlug(
          data.slug
        ),
      };

    if (
      normalizedData.slug.length <
      3
    ) {
      alert(
        "O slug deve possuir pelo menos 3 caracteres válidos."
      );

      return;
    }

    onSubmit(
      normalizedData
    );
  }
  
  return (
    <S.Form
      onSubmit={handleSubmit(
        handleFormSubmit
      )}
    >
      <ProjectInfo
        register={
          register
        }
        errors={
          errors
        }
        fieldErrors={
          fieldErrors
        }
        onSlugChange={
          handleSlugChange
        }
      />

      <ProjectCover
        featuredImage={
          featuredImage
        }
        uploading={
          uploading
        }
        onUpload={
          handleCoverUpload
        }
        onRemove={
          handleCoverRemove
        }
      />

      <ProjectGallery
        images={
          images
        }
        uploading={
          uploading
        }
        onUpload={
          handleGalleryUpload
        }
        onRemove={
          removeImage
        }
      />

      <ProjectSettings
        register={
          register
        }
      />

      <S.Actions>
        <button
          type="submit"
          disabled={
            loading ||
            uploading
          }
        >
          {loading
            ? "Salvando..."
            : uploading
              ? "Enviando imagens..."
              : project
                ? "Atualizar Projeto"
                : "Salvar Projeto"}
        </button>
      </S.Actions>
    </S.Form>
  );
}